In [33]:
# 화자분리 텍스트 -> DataFrame -> JSON -> prompt(명령)-> LLM -> 요약 
# 화자분리 텍스트 -> LLM(교정) -> 최종 회의록 생성(ms word)

In [34]:
# 화자분리된 텍스트 dataframe으로 loading
import pandas as pd

meeting_note_csv_path="../sec03/싼기타_비싼기타_final.csv"
df_rttm = pd.read_csv(meeting_note_csv_path, sep="|")

df_rttm

,start,end,speaker_id,duration,text
0,0.976,30.195,SPEAKER_01,29.219,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...
1,32.419,41.638,SPEAKER_00,9.219,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...
2,41.638,42.453,SPEAKER_01,0.815,NaN
3,41.655,42.725,SPEAKER_00,1.070,네 맞아요. 준비 되셨나요?\n
4,42.674,44.032,SPEAKER_01,1.358,네 됐어요. 시작하시죠.\n
5,45.798,67.105,SPEAKER_00,21.307,좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\...
6,67.224,82.793,SPEAKER_01,15.569,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\..."
7,84.643,102.572,SPEAKER_00,17.929,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...
8,103.489,117.530,SPEAKER_01,14.041,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...
9,119.737,138.667,SPEAKER_00,18.930,"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루..."
10,139.346,168.956,SPEAKER_01,29.610,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...
11,170.925,192.318,SPEAKER_00,21.393,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타...
12,192.317,193.692,SPEAKER_01,1.375,NaN
13,192.776,193.523,SPEAKER_00,0.747,NaN
14,193.812,216.579,SPEAKER_01,22.767,아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니...
15,218.565,237.767,SPEAKER_00,19.202,"측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다. 하하, 비싼 기타가 일종의 ..."
16,238.107,238.667,SPEAKER_01,0.560,NaN
17,238.175,239.346,SPEAKER_00,1.171,결국은 본인이 선택한...\n
18,239.856,240.654,SPEAKER_01,0.798,NaN
19,240.314,241.010,SPEAKER_00,0.696,NaN
20,241.044,251.316,SPEAKER_01,10.272,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...
21,253.659,271.553,SPEAKER_00,17.894,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...
22,272.148,304.541,SPEAKER_01,32.393,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타...
23,306.986,326.035,SPEAKER_00,19.049,하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요\n하지만 비싼 기타로...
24,326.358,335.459,SPEAKER_01,9.101,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...
25,337.547,355.934,SPEAKER_00,18.387,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...
26,356.256,363.981,SPEAKER_01,7.725,"아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n"
27,365.968,381.435,SPEAKER_00,15.467,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게..."
28,382.165,383.727,SPEAKER_01,1.562,어? 지금 도망가시는 건가요?\n
29,385.713,397.174,SPEAKER_00,11.461,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...
30,397.615,399.092,SPEAKER_01,1.477,NaN
31,401.435,406.596,SPEAKER_00,5.161,아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n
32,407.326,408.345,SPEAKER_01,1.019,화난 것 같은데?\n
33,410.093,417.445,SPEAKER_00,7.352,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으..."
34,417.750,421.230,SPEAKER_01,3.480,화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n
35,423.642,429.346,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n

In [35]:
# 이름 넣기
name_dict = {
    "SPEAKER_00":"AI",
    "SPEAKER_01":"YUN"
}

# df_rttm["name"] = df_rttm["speaker_id"].apply(처리함수)
df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict[x])

df_rttm

,start,end,speaker_id,duration,text,name
0,0.976,30.195,SPEAKER_01,29.219,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...,YUN
1,32.419,41.638,SPEAKER_00,9.219,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.638,42.453,SPEAKER_01,0.815,NaN,YUN
3,41.655,42.725,SPEAKER_00,1.070,네 맞아요. 준비 되셨나요?\n,AI
4,42.674,44.032,SPEAKER_01,1.358,네 됐어요. 시작하시죠.\n,YUN
5,45.798,67.105,SPEAKER_00,21.307,좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\...,AI
6,67.224,82.793,SPEAKER_01,15.569,"아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\...",YUN
7,84.643,102.572,SPEAKER_00,17.929,그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않...,AI
8,103.489,117.530,SPEAKER_01,14.041,싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요...,YUN
9,119.737,138.667,SPEAKER_00,18.930,"하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루...",AI
10,139.346,168.956,SPEAKER_01,29.610,충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\...,YUN
11,170.925,192.318,SPEAKER_00,21.393,하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타...,AI
12,192.317,193.692,SPEAKER_01,1.375,NaN,YUN
13,192.776,193.523,SPEAKER_00,0.747,NaN,AI
14,193.812,216.579,SPEAKER_01,22.767,아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니...,YUN
15,218.565,237.767,SPEAKER_00,19.202,"측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다. 하하, 비싼 기타가 일종의 ...",AI
16,238.107,238.667,SPEAKER_01,0.560,NaN,YUN
17,238.175,239.346,SPEAKER_00,1.171,결국은 본인이 선택한...\n,AI
18,239.856,240.654,SPEAKER_01,0.798,NaN,YUN
19,240.314,241.010,SPEAKER_00,0.696,NaN,AI
20,241.044,251.316,SPEAKER_01,10.272,근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\...,YUN
21,253.659,271.553,SPEAKER_00,17.894,맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서...,AI
22,272.148,304.541,SPEAKER_01,32.393,아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타...,YUN
23,306.986,326.035,SPEAKER_00,19.049,하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요\n하지만 비싼 기타로...,AI
24,326.358,335.459,SPEAKER_01,9.101,맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 ...,YUN
25,337.547,355.934,SPEAKER_00,18.387,그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역...,AI
26,356.256,363.981,SPEAKER_01,7.725,"아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n",YUN
27,365.968,381.435,SPEAKER_00,15.467,"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게...",AI
28,382.165,383.727,SPEAKER_01,1.562,어? 지금 도망가시는 건가요?\n,YUN
29,385.713,397.174,SPEAKER_00,11.461,아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\...,AI
30,397.615,399.092,SPEAKER_01,1.477,NaN,YUN
31,401.435,406.596,SPEAKER_00,5.161,아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n,AI
32,407.326,408.345,SPEAKER_01,1.019,화난 것 같은데?\n,YUN
33,410.093,417.445,SPEAKER_00,7.352,"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으...",AI
34,417.750,421.230,SPEAKER_01,3.480,화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n,YUN
35,423.642,429.346,SPEAKER_00,5.704,알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n,AI

In [36]:
df_rttm.head(3)

,start,end,speaker_id,duration,text,name
0,0.976,30.195,SPEAKER_01,29.219,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...,YUN
1,32.419,41.638,SPEAKER_00,9.219,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.638,42.453,SPEAKER_01,0.815,NaN,YUN

In [37]:
meeting_note_txt = df_rttm[["start","end","text","name"]].to_json(orient="records", force_ascii=False)
meeting_note_txt

'[{"start":0.976,"end":30.195,"text":"지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요 자연스럽게\\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\\n이거를 입장을 나눠가지고\\n저랑 토론해보면 좋을 것 같아요.\\n두 중에 어떤 역할 맡으실래요?\\n","name":"YUN"},{"start":32.419,"end":41.638,"text":"좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\\n","name":"AI"},{"start":41.638,"end":42.453,"text":null,"name":"YUN"},{"start":41.655,"end":42.725,"text":"네 맞아요. 준비 되셨나요?\\n","name":"AI"},{"start":42.674,"end":44.032,"text":"네 됐어요. 시작하시죠.\\n","name":"YUN"},{"start":45.798,"end":67.105,"text":"좋아요.\\n먼저 3기타로 시작하는게\\n좋은 이유를 말씀드리겠습니다.\\n초보자일때는\\n실수도 많고 기타에 익숙해지는\\n과정이 필요하니까 비싼 기타보다는\\n부담없이 연습할 수 있는\\n싼 기타가 좋다고 봅니다.\\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\\n성형님은 어떻게 생각하세요?\\n","name":"AI"},{"start":67.224,"end":82.793,"text":"아, 저는 지금 말에 어폐가 있다고 생각해요.\\n왜냐하면 어차피 지금 비싼 기타로\\n나중에 살 생각을 하는 거잖아요.\\n그럼 어차피 비싼 기타로 사고 싼 기타로 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\\n","name":"YUN"},{"start":84.643,"end":102.572,"text":"그런데 비싼 기타로 시작하면\\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\\n초보 때는 실습을 많이 하니까\\n쌍기타로 마음 편히 연습할 수 있는게\\n더 좋다고 생각해요.\\n그리고 기타 현지에 익숙해지면\\n그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\\n","name":"AI"},{"start":103.489,"end":117.53,"text":"싼 기타를 뭐하러 또 삽니까?\\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\\n기타를 싼 거 산다고 달라지나요?\\n","name":"YUN"},{"start":119.737,"end":138.667,"text":"하하, 기타를 망치로 치진 않지만\\n그래도 초보자들은 실수도 많고\\n조심스럽게 다루기 어려울 수 있잖아요.\\n비싼 기타를 사기 전에\\n부담없이 연습하면서\\n자신감을 키우는 것도 중요하다고 생각해요\\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\\n그리고 쌍기타도 요즘은\\n품질이 꽤 좋아서 연습용으로\\n","name":"AI"},{"start":139.346,"end":168.956,"text":"충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\\n많이 좋아서\\n연습하는데 충분한 거는\\n맞는데\\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\\n근데 기타가 좋은 기타다.\\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\\n","name":"YUN"},{"start":170.925,"end":192.318,"text":"하하\\n역시 좋은 기타를 사면 책임감도\\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\\n쌍기타로 시작해서\\n부담없이 연습하고\\n정말 기타에 흥미가 생기면 그때 비슷하게 부담 없이 연습하고\\n정말 기타에 흥미가 생기면\\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\\n","name":"AI"},{"start":192.317,"end":193.692,"text":null,"name":"YUN"},{"start":192.776,"end":193.523,"text":null,"name":"AI"},{"start":193.812,"end":216.579,"text":"아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\\n라는 생각이 들면서 계속\\n연습을 열심히 할 수가 있어요.\\n그래서 포기를 안 하게 되는\\n","name":"YUN"},{"start":218.565,"end":237.767,"text":"측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다. 하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\\n","name":"AI"},{"start":238.107,"end":238.667,"text":null,"name":"YUN"},{"start":238.175,"end":239.346,"text":"결국은 본인이 선택한...\\n","name":"AI"},{"start":239.856,"end":240.654,"text":null,"name":"YUN"},{"start":240.314,"end":241.01,"text":null,"name":"AI"},{"start":241.044,"end":251.316,"text":"근데 그게 비싼 기타를 치면 더 편해요.\\n편하게 치는 게 중요하다고 하셨잖아요.\\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\\n","name":"YUN"},{"start":253.659,"end":271.553,"text":"맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\\n결국 각자의 스타일과 상황에 맞게\\n선택하는 게 최선이겠네요.\\n","name":"AI"},{"start":272.148,"end":304.541,"text":"아 그 말에 대해 동의를 합니다.\\n기타를 잘 못 치는 사람은\\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\\n이걸 잘 못 느끼긴 하죠.\\n근데 반대로\\n비싼 기타를 치던 사람이\\n싼 기타를 치면은 아 이게\\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\\n그래서 처음부터 비싼 기타를 쳐서\\n그런 쌍기타의 맛을 모르고 살아도 되는데\\n왜 그 맛없는 맛을\\n굳이 초반부터 느끼려고 합니까?\\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\\n","name":"YUN"},{"start":306.986,"end":326.035,"text":"하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요\\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?\\n","name":"AI"},{"start":326.358,"end":335.459,"text":"맞아요. 그래서 비싼 기타를 사야 되는 거예요.\\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\\n왜냐면 감촉도 훨씬 좋고 그러니까요.\\n","name":"YUN"},{"start":337.547,"end":355.934,"text":"그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\\n","name":"AI"},{"start":356.256,"end":363.981,"text":"아, 맞아요.\\n지금 얘기하신 거 보니까\\n쌍기타가 더 좋다는 얘기는 안 하시네요.\\n","name":"YUN"},{"start":365.968,"end":381.435,"text":"아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\\n재밌게 이야기 나누는 게 더 중요한 것 같아요.\\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\\n앞으로도 즐겁게 연습하시길 바래요.\\n","name":"AI"},{"start":382.165,"end":383.727,"text":"어? 지금 도망가시는 건가요?\\n","name":"YUN"},{"start":385.713,"end":397.174,"text":"아니요. 전혀 그렇지 않아요.\\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\\n","name":"AI"},{"start":397.615,"end":399.092,"text":null,"name":"YUN"},{"start":401.435,"end":406.596,"text":"아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\\n","name":"AI"},{"start":407.326,"end":408.345,"text":"화난 것 같은데?\\n","name":"YUN"},{"start":410.093,"end":417.445,"text":"네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\\n계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요.\\n아니요.\\n","name":"AI"},{"start":417.75,"end":421.23,"text":"화나셨는데 굳이 더 할 필요 없죠.\\n그만 잊지 마시죠.\\n","name":"YUN"},{"start":423.642,"end":429.346,"text":"알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\\n","name":"AI"}]'

In [38]:
# system prompt
system_prompt = f'''
    너는 회의 내용을 요약하는 봇이다.
    아래 회의록을 읽고, 주요 내용을 요약하라.
    결과는 마크다운 형식으로 작성한다.

    아래 형식에 맞추어 작성하라.
    # 회의 제목

    ## 주요 내용

    ## 참석자별 입장

    ## 결정 사항

    ================= 이하 회의록 =================
    {meeting_note_txt}
'''

In [39]:
# OpenAI CHAT API
import os
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
api_key = os.getenv("OPENAPI_AI_KEY")

client = OpenAI(api_key=api_key)    # client => llm => response

In [40]:
response=client.chat.completions.create(
    model="gpt-4o",
    temperature=0.1,
    messages=[
        {"role":"system", "content":system_prompt}
    ]
)
response

ChatCompletion(id='chatcmpl-EU0nIDFAwXUNN8r3B1qGmhAnqjBdC', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='# 회의 제목\n\n기타 구매 시 싼 기타와 비싼 기타 중 어떤 것이 더 나은 선택인가?\n\n## 주요 내용\n\n- 기타를 처음 시작할 때 싼 기타로 시작하는 것이 좋은지, 비싼 기타로 시작하는 것이 좋은지에 대한 토론이 진행됨.\n- 싼 기타의 장점으로는 부담 없이 연습할 수 있고, 초보자에게 적합하다는 점이 강조됨.\n- 비싼 기타의 장점으로는 더 나은 소리와 연주 경험을 제공하며, 동기부여가 될 수 있다는 점이 언급됨.\n- 각자의 상황과 스타일에 맞는 선택이 중요하다는 결론에 도달함.\n\n## 참석자별 입장\n\n- **YUN**: 비싼 기타로 시작하는 것이 이중 지출을 막고, 더 나은 연주 경험을 제공하며, 동기부여가 될 수 있다고 주장.\n- **AI**: 싼 기타로 시작하는 것이 부담 없이 연습할 수 있고, 초보자에게 적합하다고 주장.\n\n## 결정 사항\n\n- 기타를 선택할 때는 개인의 스타일과 상황에 맞게 선택하는 것이 중요하며, 꾸준한 연습과 열정이 가장 중요하다는 결론에 도달함.', refusal=None, role='assistant', annotations=[], audio=None, function_call=None, tool_calls=None))], created=1790821600, model='gpt-4o-2024-08-06', object='chat.completion', metadata=None, moderation=None, service_tier='default', system_fingerprint='fp_95d3055667', usage=CompletionUsage(completion_tokens=277, prompt_tokens=3006, total_tokens=3283, completion_tokens_details=CompletionTokensDetails(accepted_prediction_tokens=0, audio_tokens=0, reasoning_tokens=0, rejected_prediction_tokens=0, text_tokens=None), prompt_tokens_details=PromptTokensDetails(audio_tokens=0, cache_write_tokens=None, cached_tokens=0, image_tokens=None, text_tokens=None)))

In [41]:
print(response.choices[0].message.content)

# 회의 제목

기타 구매 시 싼 기타와 비싼 기타 중 어떤 것이 더 나은 선택인가?

## 주요 내용

- 기타를 처음 시작할 때 싼 기타로 시작하는 것이 좋은지, 비싼 기타로 시작하는 것이 좋은지에 대한 토론이 진행됨.
- 싼 기타의 장점으로는 부담 없이 연습할 수 있고, 초보자에게 적합하다는 점이 강조됨.
- 비싼 기타의 장점으로는 더 나은 소리와 연주 경험을 제공하며, 동기부여가 될 수 있다는 점이 언급됨.
- 각자의 상황과 스타일에 맞는 선택이 중요하다는 결론에 도달함.

## 참석자별 입장

- **YUN**: 비싼 기타로 시작하는 것이 이중 지출을 막고, 더 나은 연주 경험을 제공하며, 동기부여가 될 수 있다고 주장.
- **AI**: 싼 기타로 시작하는 것이 부담 없이 연습할 수 있고, 초보자에게 적합하다고 주장.

## 결정 사항

- 기타를 선택할 때는 개인의 스타일과 상황에 맞게 선택하는 것이 중요하며, 꾸준한 연습과 열정이 가장 중요하다는 결론에 도달함.

In [42]:
summary=response.choices[0].message.content
summary=summary.strip() # 양쪽 공백 제거
# 파일에 저장
with open("../audio/guitar_summary2.md", "w", encoding="utf-8") as f:
    f.write(summary)

In [43]:
# 화자분리 텍스트 -> LLM(교정) -> 최종 회의록 생성(ms word)
df_rttm.head()

,start,end,speaker_id,duration,text,name
0,0.976,30.195,SPEAKER_01,29.219,지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 ...,YUN
1,32.419,41.638,SPEAKER_00,9.219,좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님...,AI
2,41.638,42.453,SPEAKER_01,0.815,NaN,YUN
3,41.655,42.725,SPEAKER_00,1.070,네 맞아요. 준비 되셨나요?\n,AI
4,42.674,44.032,SPEAKER_01,1.358,네 됐어요. 시작하시죠.\n,YUN

In [ ]:
df_meeting_note = df_rttm[["start","end","text","name"]].copy()
# 데이터 전처리 => 교정
# NaN 제거
df_meeting_note.dropna(inplace=True)    # inplace=True: 원본에 반영
# df_meeting_note = df_meeting_note.dropna(inplace=False) False: 삭제한 결과 df를 반환

In [48]:
# 데이터프레임 => 딕셔너리
meeting_note_dict = df_meeting_note.to_dict(orient="records")   # orient="records": 각 행을 독립된 dictionary로 생성 => 리스트로 묶는다.
meeting_note_dict

[{'start': 0.976,
  'end': 30.195,
  'text': '지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요 자연스럽게\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n두 중에 어떤 역할 맡으실래요?\n',
  'name': 'YUN'},
 {'start': 32.419,
  'end': 41.638000000000005,
  'text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\n',
  'name': 'AI'},
 {'start': 41.638, 'end': 42.453, 'text': nan, 'name': 'YUN'},
 {'start': 41.655, 'end': 42.725, 'text': '네 맞아요. 준비 되셨나요?\n', 'name': 'AI'},
 {'start': 42.674, 'end': 44.032, 'text': '네 됐어요. 시작하시죠.\n', 'name': 'YUN'},
 {'start': 45.798,
  'end': 67.105,
  'text': '좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는\n부담없이 연습할 수 있는\n싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n',
  'name': 'AI'},
 {'start': 67.224,
  'end': 82.79299999999999,
  'text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타로 사고 싼 기타로 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n',
  'name': 'YUN'},
 {'start': 84.643,
  'end': 102.572,
  'text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\n초보 때는 실습을 많이 하니까\n쌍기타로 마음 편히 연습할 수 있는게\n더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\n',
  'name': 'AI'},
 {'start': 103.489,
  'end': 117.53,
  'text': '싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?\n',
  'name': 'YUN'},
 {'start': 119.737,
  'end': 138.667,
  'text': '하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\n그리고 쌍기타도 요즘은\n품질이 꽤 좋아서 연습용으로\n',
  'name': 'AI'},
 {'start': 139.346,
  'end': 168.956,
  'text': '충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\n',
  'name': 'YUN'},
 {'start': 170.925,
  'end': 192.318,
  'text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n쌍기타로 시작해서\n부담없이 연습하고\n정말 기타에 흥미가 생기면 그때 비슷하게 부담 없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\n',
  'name': 'AI'},
 {'start': 192.317, 'end': 193.692, 'text': nan, 'name': 'YUN'},
 {'start': 192.776, 'end': 193.523, 'text': nan, 'name': 'AI'},
 {'start': 193.812,
  'end': 216.579,
  'text': '아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n',
  'name': 'YUN'},
 {'start': 218.565,
  'end': 237.767,
  'text': '측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다. 하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n',
  'name': 'AI'},
 {'start': 238.107, 'end': 238.667, 'text': nan, 'name': 'YUN'},
 {'start': 238.175, 'end': 239.346, 'text': '결국은 본인이 선택한...\n', 'name': 'AI'},
 {'start': 239.856, 'end': 240.654, 'text': nan, 'name': 'YUN'},
 {'start': 240.314, 'end': 241.01, 'text': nan, 'name': 'AI'},
 {'start': 241.044,
  'end': 251.316,
  'text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n',
  'name': 'YUN'},
 {'start': 253.659,
  'end': 271.553,
  'text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.\n',
  'name': 'AI'},
 {'start': 272.148,
  'end': 304.541,
  'text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\n',
  'name': 'YUN'},
 {'start': 306.986,
  'end': 326.035,
  'text': '하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?\n',
  'name': 'AI'},
 {'start': 326.358,
  'end': 335.459,
  'text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n',
  'name': 'YUN'},
 {'start': 337.547,
  'end': 355.934,
  'text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n',
  'name': 'AI'},
 {'start': 356.256,
  'end': 363.981,
  'text': '아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n',
  'name': 'YUN'},
 {'start': 365.968,
  'end': 381.435,
  'text': '아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요.\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n',
  'name': 'AI'},
 {'start': 382.165,
  'end': 383.727,
  'text': '어? 지금 도망가시는 건가요?\n',
  'name': 'YUN'},
 {'start': 385.713,
  'end': 397.174,
  'text': '아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\n',
  'name': 'AI'},
 {'start': 397.615, 'end': 399.092, 'text': nan, 'name': 'YUN'},
 {'start': 401.435,
  'end': 406.596,
  'text': '아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n',
  'name': 'AI'},
 {'start': 407.326, 'end': 408.345, 'text': '화난 것 같은데?\n', 'name': 'YUN'},
 {'start': 410.093,
  'end': 417.445,
  'text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요.\n아니요.\n',
  'name': 'AI'},
 {'start': 417.75,
  'end': 421.23,
  'text': '화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n',
  'name': 'YUN'},
 {'start': 423.642,
  'end': 429.346,
  'text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n',
  'name': 'AI'}]

In [50]:
for row in meeting_note_dict:   # 한 행씩 처리
    # 한 개의 dictionary 안에 있는 text 가져와서 type이 str인지 확인(LLM은 text만 받음.)
    if not isinstance(row["text"], str):
        continue
    # 교정하는 코드: 텍스트(row) => LLM => 교정(correction)
    # 1. correction_system_prompt: 페르소나 + 명령 + text(한 행) + summary + 녹취 전문
    correction_system_prompt = f'''
        rules = 너는 STT 녹취록 교정기다. 규칙:
        1) 잘못 받아적은 단어만 고친다. 말투·어순·내용은 바꾸지 않는다.
        2) 확신이 없으면 원문을 그대로 둔다.
        3) 입력과 같은 id를 가진 JSON만 출력한다: {"items":[{"id":0,"corrected":"..."}, ...]}

        ---------------------------------------------
        회의 요약문 : {summary}
        ---------------------------------------------
        회의 녹취록 전문: {df_meeting_note.to_json(orient="records",force_ascii=False)}
        ---------------------------------------------
        확인할 메시지 원본: {row["text"]}
    '''
    # end prompt
    # 2. response
    response = client.chat.completions.create(
        model="gpt-6-astra",     # token limit : 분당 30000
        # temperature=0.1,    # 
        messages=[
            {"role":"system","content":correction_system_prompt}
        ]
    )

    correction = response.choices[0].message.content    # 한 개 행에 대한 교정 결과
    if ":" in correction:   # "수정 ':' 내용"과 같은 형식으로 반환되는 경우 해결? 너무 지엽적인 느낌....
        correction = correction.split(":")[-1]

    correction = correction.strip()

    print(row["name"])  # 누가 말했고 출력
    print(row["text"])  # 교정 전 원본
    print(correction)   # 교정된 대화
    print("-"*100)

    row["corrected_text"] = correction  # row: 딕셔너리, 'corrected_text' 키에 값은 correction

YUN
지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요 자연스럽게
그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
두 중에 어떤 역할 맡으실래요?

지금부터 저랑 그 역할극을 합시다. 역할극을 스탠드업 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요, 자연스럽게.
그리고 주제는 싼 기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
둘 중에 어떤 역할 맡으실래요?
----------------------------------------------------------------------------------------------------
AI
좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?

좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 선생님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?
----------------------------------------------------------------------------------------------------
AI
네 맞아요. 준비 되셨나요?

네, 맞아요. 준비되셨나요?
----------------------------------------------------------------------------------------------------
YUN
네 됐어요. 시작하시죠.

네 됐어요. 시작하시죠.
----------------------------------------------------------------------------------------------------
AI
좋아요.
먼저 3기타로 시작하는게
좋은 이유를 말씀드리겠습니다.
초보자일때는
실수도 많고 기타에 익숙해지는
과정이 필요하니까 비싼 기타보다는
부담없이 연습할 수 있는
싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?
성형님은 어떻게 생각하세요?

좋아요.
먼저 싼 기타로 시작하는 게
좋은 이유를 말씀드리겠습니다.
초보자일 때는
실수도 많고 기타에 익숙해지는
과정이 필요하니까 비싼 기타보다는
부담 없이 연습할 수 있는
싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드하는 것도 나쁘지 않죠?
성형님은 어떻게 생각하세요?
----------------------------------------------------------------------------------------------------
YUN
아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타로
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타로 사고 싼 기타로 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.

아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타를
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타도 사고 싼 기타도 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면 이중 지출을 막을 수가 있습니다.
----------------------------------------------------------------------------------------------------
AI
그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 실습을 많이 하니까 더 크지 않을까요?
초보 때는 실습을 많이 하니까
쌍기타로 마음 편히 연습할 수 있는게
더 좋다고 생각해요.
그리고 기타 현지에 익숙해지면
그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데

그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 실수를 많이 하니까
싼 기타로 마음 편히 연습할 수 있는 게
더 좋다고 생각해요.
그리고 기타 연주에 익숙해지면
그때 비싼 기타를 사는 게 더 의미 있지 않을까요?
----------------------------------------------------------------------------------------------------
YUN
싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데
기타를 싼 거 산다고 달라지나요?

아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데
기타를 싼 거 산다고 달라지나요?
----------------------------------------------------------------------------------------------------
AI
하하, 기타를 망치로 치진 않지만
그래도 초보자들은 실수도 많고
조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에
부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요
그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.
그리고 쌍기타도 요즘은
품질이 꽤 좋아서 연습용으로

하하, 기타를 망치로 치진 않지만
그래도 초보자들은 실수도 많고
조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에
부담없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요.
그리고 싼 기타도 요즘은
품질이 꽤 좋아서 연습용으로 충분하죠.
----------------------------------------------------------------------------------------------------
YUN
충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이
많이 좋아서
연습하는데 충분한 거는
맞는데
근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?
그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.
근데 기타가 좋은 기타다.
그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요

아 맞아요. 그것도 맞는 말이에요. 싼 기타도 요새 품질이
많이 좋아서
연습하는 데 충분한 거는
맞는데
근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?
그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.
근데 기타가 좋은 기타다.
그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요
----------------------------------------------------------------------------------------------------
AI
하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.
쌍기타로 시작해서
부담없이 연습하고
정말 기타에 흥미가 생기면 그때 비슷하게 부담 없이 연습하고
정말 기타에 흥미가 생기면
그때 비싼 기타로 넘어가는 것도 좋은 방법이죠

하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요. 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.
싼 기타로 시작해서
부담 없이 연습하고
정말 기타에 흥미가 생기면
그때 비싼 기타로 넘어가는 것도 좋은 방법이죠
----------------------------------------------------------------------------------------------------
YUN
아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?
라는 생각이 들면서 계속
연습을 열심히 할 수가 있어요.
그래서 포기를 안 하게 되는

아니에요. 왜냐하면 싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 잃게 돼요. 그리고 비싼 기타를 사면은 흥미를 잃게 되더라도 어, 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?
라는 생각이 들면서 계속
연습을 열심히 할 수가 있어요.
그래서 포기를 안 하게 되는 측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다.
----------------------------------------------------------------------------------------------------
AI
측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다. 하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.
하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.
그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.

하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.
하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.
그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.
----------------------------------------------------------------------------------------------------
AI
결국은 본인이 선택한...

결국은 본인이 선택한...
----------------------------------------------------------------------------------------------------
YUN
근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.

근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇겠어요?
----------------------------------------------------------------------------------------------------
AI
맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게
선택하는 게 최선이겠네요.

맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 싼 기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게
선택하는 게 최선이겠네요.
----------------------------------------------------------------------------------------------------
YUN
아 그 말에 대해 동의를 합니다.
기타를 잘 못 치는 사람은
쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로
비싼 기타를 치던 사람이
싼 기타를 치면은 아 이게
이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다
그래서 처음부터 비싼 기타를 쳐서
그런 쌍기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작을 하는 게 좋죠.

아 그 말에 대해 동의를 합니다.
기타를 잘 못 치는 사람은
싼 기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로
비싼 기타를 치던 사람이
싼 기타를 치면은 아 이게
이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다.
그래서 처음부터 비싼 기타를 쳐서
그런 싼 기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작을 하는 게 좋죠.
----------------------------------------------------------------------------------------------------
AI
하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?

하하! 싼 기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?
----------------------------------------------------------------------------------------------------

RateLimitError: Error code: 429 - {'error': {'message': 'You have no credits remaining. Add credits to continue using the API at https://platform.openai.com/settings/organization/billing/.', 'type': 'insufficient_quota', 'param': None, 'code': 'credit_balance_exhausted'}}

In [ ]:
# meeting_note_dict: correction_text가 있는 리스트 -> json 파일 생성
# meeting_note_dict json 파일로 저장
# import json


# with open('../audio/guitar_meeting_note_corrected_02.json', 'w', encoding='utf-8') as f:
#     json.dump(meeting_note_dict, f, ensure_ascii=False, indent=4)

In [54]:
import pickle


with open('../audio/meeting_note_dict.pickle', 'rb') as f:
    meeting_note_dict = pickle.load(f)

In [57]:
meeting_note_dict

[{'start': 0.976,
  'end': 30.195,
  'text': '지금부터 저랑 그 역할극을 합시다 역할극을 스탠딩 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요 자연스럽게\n그리고 주제는 쌍기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n두 중에 어떤 역할 맡으실래요?\n',
  'name': 'HAPPYDAY',
  'correction_text': '지금부터 저랑 그 역할극을 합시다 역할극을 스탠드업 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.\n그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요 자연스럽게\n그리고 주제는 싼 기타로 전기기타를 시작하는 게 좋으냐\n아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐\n이거를 입장을 나눠가지고\n저랑 토론해보면 좋을 것 같아요.\n둘 중에 어떤 역할 맡으실래요?'},
 {'start': 32.419,
  'end': 41.638000000000005,
  'text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 성형님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?\n',
  'name': 'AI',
  'correction_text': '좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 선생님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?'},
 {'start': 41.655,
  'end': 42.725,
  'text': '네 맞아요. 준비 되셨나요?\n',
  'name': 'AI',
  'correction_text': '네, 맞아요. 준비되셨나요?'},
 {'start': 42.674,
  'end': 44.032,
  'text': '네 됐어요. 시작하시죠.\n',
  'name': 'HAPPYDAY',
  'correction_text': '네 됐어요. 시작하시죠.'},
 {'start': 45.798,
  'end': 67.105,
  'text': '좋아요.\n먼저 3기타로 시작하는게\n좋은 이유를 말씀드리겠습니다.\n초보자일때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는\n부담없이 연습할 수 있는\n싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드 하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?\n',
  'name': 'AI',
  'correction_text': '좋아요.\n먼저 싼 기타로 시작하는 게\n좋은 이유를 말씀드리겠습니다.\n초보자일 때는\n실수도 많고 기타에 익숙해지는\n과정이 필요하니까 비싼 기타보다는\n부담 없이 연습할 수 있는\n싼 기타가 좋다고 봅니다.\n무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드하는 것도 나쁘지 않죠?\n성형님은 어떻게 생각하세요?'},
 {'start': 67.224,
  'end': 82.79299999999999,
  'text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타로\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타로 사고 싼 기타로 사게 되는데 그런 이중 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중지출을 하지 말고 처음부터 비싼 기타로 가면 이중지출을 막을 수가 있습니다.\n',
  'name': 'HAPPYDAY',
  'correction_text': '아, 저는 지금 말에 어폐가 있다고 생각해요.\n왜냐하면 어차피 지금 비싼 기타를\n나중에 살 생각을 하는 거잖아요.\n그럼 어차피 비싼 기타도 사고 싼 기타도 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중 지출을 막을 수가 있습니다.'},
 {'start': 84.643,
  'end': 102.572,
  'text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실습을 많이 하니까 더 크지 않을까요?\n초보 때는 실습을 많이 하니까\n쌍기타로 마음 편히 연습할 수 있는게\n더 좋다고 생각해요.\n그리고 기타 현지에 익숙해지면\n그때 비싼 기타를 사는게 더 의미있지 않을까요? 아니 근데 어차피 비싼 기타를 살 건데\n',
  'name': 'AI',
  'correction_text': '그런데 비싼 기타로 시작하면\n혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?\n초보 때는 실수를 많이 하니까\n싼 기타로 마음 편히 연습할 수 있는 게\n더 좋다고 생각해요.\n그리고 기타 연주에 익숙해지면\n그때 비싼 기타를 사는 게 더 의미 있지 않을까요?'},
 {'start': 103.489,
  'end': 117.53,
  'text': '싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?\n',
  'name': 'HAPPYDAY',
  'correction_text': '아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?\n그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.\n기타를 망치로 치는 것도 아니라 손가락으로 치는 건데\n기타를 싼 거 산다고 달라지나요?'},
 {'start': 119.737,
  'end': 138.667,
  'text': '하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요\n그리고 싼 기타도 요즘은 하는 것도 중요하다고 생각해요.\n그리고 쌍기타도 요즘은\n품질이 꽤 좋아서 연습용으로\n',
  'name': 'AI',
  'correction_text': '하하, 기타를 망치로 치진 않지만\n그래도 초보자들은 실수도 많고\n조심스럽게 다루기 어려울 수 있잖아요.\n비싼 기타를 사기 전에\n부담 없이 연습하면서\n자신감을 키우는 것도 중요하다고 생각해요.\n그리고 싼 기타도 요즘은\n품질이 꽤 좋아서 연습용으로 충분하죠.'},
 {'start': 139.346,
  'end': 168.956,
  'text': '충분하죠. 아 맞아요. 그것도 맞는 말이에요. 쌍기타도 요새 품질이\n많이 좋아서\n연습하는데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요\n',
  'name': 'HAPPYDAY',
  'correction_text': '아 맞아요. 그것도 맞는 말이에요. 싼 기타도 요새 품질이\n많이 좋아서\n연습하는 데 충분한 거는\n맞는데\n근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?\n그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.\n근데 기타가 좋은 기타다.\n그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요'},
 {'start': 170.925,
  'end': 192.318,
  'text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n쌍기타로 시작해서\n부담없이 연습하고\n정말 기타에 흥미가 생기면 그때 비슷하게 부담 없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠\n',
  'name': 'AI',
  'correction_text': '하하\n역시 좋은 기타를 사면 책임감도\n더 커진다는 말씀이시군요. 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.\n싼 기타로 시작해서\n부담 없이 연습하고\n정말 기타에 흥미가 생기면\n그때 비싼 기타로 넘어가는 것도 좋은 방법이죠'},
 {'start': 193.812,
  'end': 216.579,
  'text': '아니에요. 왜냐하면 비싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 이렇게 돼요 그리고 비싼 기타를 사면 은 흥미를 잃게 되더라도 어 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는\n',
  'name': 'HAPPYDAY',
  'correction_text': '아니에요. 왜냐하면 싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 잃게 돼요. 그리고 비싼 기타를 사면은 흥미를 잃게 되더라도 어, 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?\n라는 생각이 들면서 계속\n연습을 열심히 할 수가 있어요.\n그래서 포기를 안 하게 되는 측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다.'},
 {'start': 218.565,
  'end': 237.767,
  'text': '측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다. 하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.\n',
  'name': 'AI',
  'correction_text': '하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.\n하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?\n특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.\n그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.'},
 {'start': 238.175,
  'end': 239.346,
  'text': '결국은 본인이 선택한...\n',
  'name': 'AI',
  'correction_text': '결국은 본인이 선택한...'},
 {'start': 241.044,
  'end': 251.316,
  'text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇게 해서요.\n',
  'name': 'HAPPYDAY',
  'correction_text': '근데 그게 비싼 기타를 치면 더 편해요.\n편하게 치는 게 중요하다고 하셨잖아요.\n근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇겠어요?'},
 {'start': 253.659,
  'end': 271.553,
  'text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 쌍기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.\n',
  'name': 'AI',
  'correction_text': '맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.\n하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.\n그래서 싼 기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.\n결국 각자의 스타일과 상황에 맞게\n선택하는 게 최선이겠네요.'},
 {'start': 272.148,
  'end': 304.541,
  'text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n쌍기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다\n그래서 처음부터 비싼 기타를 쳐서\n그런 쌍기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.\n',
  'name': 'HAPPYDAY',
  'correction_text': '아 그 말에 대해 동의를 합니다.\n기타를 잘 못 치는 사람은\n싼 기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지\n이걸 잘 못 느끼긴 하죠.\n근데 반대로\n비싼 기타를 치던 사람이\n싼 기타를 치면은 아 이게\n이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다.\n그래서 처음부터 비싼 기타를 쳐서\n그런 싼 기타의 맛을 모르고 살아도 되는데\n왜 그 맛없는 맛을\n굳이 초반부터 느끼려고 합니까?\n그러니까 비싼 기타로 시작을 하는 게 좋죠.'},
 {'start': 306.986,
  'end': 326.035,
  'text': '하하! 쌍기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?\n',
  'name': 'AI',
  'correction_text': '하하! 싼 기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요\n하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니\n처음엔 가볍게 접근하는 게 더 좋다고 봅니다.\n어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?'},
 {'start': 326.358,
  'end': 335.459,
  'text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.\n',
  'name': 'HAPPYDAY',
  'correction_text': '맞아요. 그래서 비싼 기타를 사야 되는 거예요.\n비싼 기타를 사면 꾸준히 연습을 하게 됩니다.\n왜냐하면 계속 그 기타를 만지고 있고 싶거든요.\n왜냐면 감촉도 훨씬 좋고 그러니까요.'},
 {'start': 337.547,
  'end': 355.934,
  'text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.\n',
  'name': 'AI',
  'correction_text': '그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.\n하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.\n결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.\n소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.'},
 {'start': 356.256,
  'end': 363.981,
  'text': '아, 맞아요.\n지금 얘기하신 거 보니까\n쌍기타가 더 좋다는 얘기는 안 하시네요.\n',
  'name': 'HAPPYDAY',
  'correction_text': '아, 맞아요.\n지금 얘기하신 거 보니까\n싼 기타가 더 좋다는 얘기는 안 하시네요.'},
 {'start': 365.968,
  'end': 381.435,
  'text': '아마 제가 이긴 거 같아요. 그렇죠? 하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요.\n가짜 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.\n',
  'name': 'AI',
  'correction_text': '하하, 토론에서 이기고 지는 것보다는\n재밌게 이야기 나누는 게 더 중요한 것 같아요.\n각자 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.\n결국 중요한 건 기타를 사랑하는 마음이겠죠.\n앞으로도 즐겁게 연습하시길 바래요.'},
 {'start': 382.165,
  'end': 383.727,
  'text': '어? 지금 도망가시는 건가요?\n',
  'name': 'HAPPYDAY',
  'correction_text': '어? 지금 도망가시는 건가요?'},
 {'start': 385.713,
  'end': 397.174,
  'text': '아니요. 전혀 그렇지 않아요.\n전엔 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요? 지금 혹시 화나셨나요?\n',
  'name': 'AI',
  'correction_text': '아니요. 전혀 그렇지 않아요.\n저는 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.\n토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.\n혹시 더 이야기하고 싶으신 게 있나요?'},
 {'start': 401.435,
  'end': 406.596,
  'text': '아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하세요.\n',
  'name': 'AI',
  'correction_text': '아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하지 마세요.'},
 {'start': 407.326,
  'end': 408.345,
  'text': '화난 것 같은데?\n',
  'name': 'HAPPYDAY',
  'correction_text': '화난 것 같은데?'},
 {'start': 410.093,
  'end': 417.445,
  'text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이하고 나누고 싶으시면 편하게 말씀해주세요.\n아니요.\n',
  'name': 'AI',
  'correction_text': '네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.\n계속해서 이야기 나누고 싶으시면 편하게 말씀해주세요.'},
 {'start': 417.75,
  'end': 421.23,
  'text': '화나셨는데 굳이 더 할 필요 없죠.\n그만 잊지 마시죠.\n',
  'name': 'HAPPYDAY',
  'correction_text': '화나셨는데 굳이 더 할 필요 없죠.\n그만하시죠.'},
 {'start': 423.642,
  'end': 429.346,
  'text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.\n',
  'name': 'AI',
  'correction_text': '알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.'}]

In [59]:
md_template = ""

for row in meeting_note_dict:
    md_template += f"- **{row['name']}** : {row['correction_text']}\n"

print(md_template)

- **HAPPYDAY** : 지금부터 저랑 그 역할극을 합시다 역할극을 스탠드업 코미디 스타일로 할 건데 토론을 하면서 자연스럽게 대화하는 형식으로 하면서 코미디를 진행해봅시다.
그래서 좀 재밌고 자연스럽고 유머러스하게 저랑 대화를 하시면 돼요 자연스럽게
그리고 주제는 싼 기타로 전기기타를 시작하는 게 좋으냐
아니면 비싼 기타로 전기기타를 시작하는 게 좋으냐
이거를 입장을 나눠가지고
저랑 토론해보면 좋을 것 같아요.
둘 중에 어떤 역할 맡으실래요?
- **AI** : 좋습니다. 그럼 제가 싼 기타로 시작하는 게 좋다는 입장을 맡아볼게요. 그럼 선생님은 비싼 기타로 시작하는 게 좋다는 입장이시죠?
- **AI** : 네, 맞아요. 준비되셨나요?
- **HAPPYDAY** : 네 됐어요. 시작하시죠.
- **AI** : 좋아요.
먼저 싼 기타로 시작하는 게
좋은 이유를 말씀드리겠습니다.
초보자일 때는
실수도 많고 기타에 익숙해지는
과정이 필요하니까 비싼 기타보다는
부담 없이 연습할 수 있는
싼 기타가 좋다고 봅니다.
무엇보다 실력이 향상되면 그때 좋은 기타로 업그레이드하는 것도 나쁘지 않죠?
성형님은 어떻게 생각하세요?
- **HAPPYDAY** : 아, 저는 지금 말에 어폐가 있다고 생각해요.
왜냐하면 어차피 지금 비싼 기타를
나중에 살 생각을 하는 거잖아요.
그럼 어차피 비싼 기타도 사고 싼 기타도 사게 되는데 그런 이중 지출을 하지 말고 처음부터 비싼 기타로 가면은 이중 지출을 막을 수가 있습니다.
- **AI** : 그런데 비싼 기타로 시작하면
혹시라도 흠집이 나거나 실수할 때 부담이 더 크지 않을까요?
초보 때는 실수를 많이 하니까
싼 기타로 마음 편히 연습할 수 있는 게
더 좋다고 생각해요.
그리고 기타 연주에 익숙해지면
그때 비싼 기타를 사는 게 더 의미 있지 않을까요?
- **HAPPYDAY** : 아니 근데 어차피 비싼 기타를 살 건데 싼 기타를 뭐하러 또 삽니까?
그리고 기타 실력이랑 흠집이랑은 아무 상관이 없어요.
기타를 망치로 치는 것도 아니라 손가락으로 치는 건데
기타를 싼 거 산다고 달라지나요?
- **AI** : 하하, 기타를 망치로 치진 않지만
그래도 초보자들은 실수도 많고
조심스럽게 다루기 어려울 수 있잖아요.
비싼 기타를 사기 전에
부담 없이 연습하면서
자신감을 키우는 것도 중요하다고 생각해요.
그리고 싼 기타도 요즘은
품질이 꽤 좋아서 연습용으로 충분하죠.
- **HAPPYDAY** : 아 맞아요. 그것도 맞는 말이에요. 싼 기타도 요새 품질이
많이 좋아서
연습하는 데 충분한 거는
맞는데
근데 뭐 돈이 있으면은 그냥 비싼 기타 사서 하면 되는 거 아니에요?
그리고 기타를 그 안 좋은 걸 사면 뭐가 문제가 있냐면 자기가 이게 뭐가 안 될 때, 안 될 때 이게 기타가 싸구려라서 안 되나? 라는 생각을 한단 말이죠.
근데 기타가 좋은 기타다.
그러면은 아 이거 내가 부족해서 기타가 이런 소리밖에 안 나는구나 라고 생각하면서 반성을 하면서 더 열심히 연습하게 된다니까요
- **AI** : 하하
역시 좋은 기타를 사면 책임감도
더 커진다는 말씀이시군요. 그래도 비싼 기타를 처음부터 사면 혹시라도 기타에 흥미가 떨어지거나 생각보다 연습시간이 적을 때 아까울 수도 있잖아요.
싼 기타로 시작해서
부담 없이 연습하고
정말 기타에 흥미가 생기면
그때 비싼 기타로 넘어가는 것도 좋은 방법이죠
- **HAPPYDAY** : 아니에요. 왜냐하면 싼 기타로 시작을 하면 연습할 때 기분이 안 나잖아요. 그러니까 흥미를 더 쉽게 잃게 돼요. 그리고 비싼 기타를 사면은 흥미를 잃게 되더라도 어, 이거 비싼 기타 샀는데 내가 여기서 포기할 수 있나?
라는 생각이 들면서 계속
연습을 열심히 할 수가 있어요.
그래서 포기를 안 하게 되는 측면에서도 비싼 기타가 훨씬 도움이 된다고 생각합니다.
- **AI** : 하하, 비싼 기타가 일종의 동기부여가 된다는 말씀이시군요.
하지만 반대로 비싼 기타 때문에 오히려 부담이 커져서 스트레스를 받을 수도 있지 않을까요?
특히 초보자들은 편하게 시작하는 게 더 중요하다고 생각해요.
그리고 좋은 기타로 나중에 업그레이드 할 때 그 성취감도 크니까요.
- **AI** : 결국은 본인이 선택한...
- **HAPPYDAY** : 근데 그게 비싼 기타를 치면 더 편해요.
편하게 치는 게 중요하다고 하셨잖아요.
근데 비싼 기타를 치면 그게 치기가 편하니까 비싼 거예요. 안 그렇겠어요?
- **AI** : 맞아요. 비싼 기타는 확실히 소리도 좋고 연주하기 편하죠.
하지만 초보자 입장에서는 그런 차이를 잘 느끼기 어려울 수도 있어요.
그래서 싼 기타로도 충분히 연습하면서 기본기를 다지는 게 중요하다고 생각해요.
결국 각자의 스타일과 상황에 맞게
선택하는 게 최선이겠네요.
- **HAPPYDAY** : 아 그 말에 대해 동의를 합니다.
기타를 잘 못 치는 사람은
싼 기타와 비싼 기타를 치더라도 이게 왜 좋은 기타인지
이걸 잘 못 느끼긴 하죠.
근데 반대로
비싼 기타를 치던 사람이
싼 기타를 치면은 아 이게
이렇게 싸구려구나 라는 걸 금방 느낄 수가 있습니다.
그래서 처음부터 비싼 기타를 쳐서
그런 싼 기타의 맛을 모르고 살아도 되는데
왜 그 맛없는 맛을
굳이 초반부터 느끼려고 합니까?
그러니까 비싼 기타로 시작을 하는 게 좋죠.
- **AI** : 하하! 싼 기타의 맛을 모르는 게 오히려 더 좋다는 말씀이시군요
하지만 비싼 기타로 시작하면 그만큼 실수나 부담도 클 수 있으니
처음엔 가볍게 접근하는 게 더 좋다고 봅니다.
어쨌든 중요한 건 꾸준히 연습하는 거니까 어떤 기타를 선택하든 열심히 연습하는 게 제일 중요하겠죠?
- **HAPPYDAY** : 맞아요. 그래서 비싼 기타를 사야 되는 거예요.
비싼 기타를 사면 꾸준히 연습을 하게 됩니다.
왜냐하면 계속 그 기타를 만지고 있고 싶거든요.
왜냐면 감촉도 훨씬 좋고 그러니까요.
- **AI** : 그렇죠. 비싼 기타는 그만큼 소리도 좋고 연주할 때 기분도 좋으니까요.
하지만 역시 중요한 건 기타를 꾸준히 연습하는 열정이겠죠.
결국 어떤 기타를 선택하든 가장 중요한 건 그 열정과 노력일 것 같아요.
소중한 기타와 함께 멋진 연주를 이어가시길 바랄게요.
- **HAPPYDAY** : 아, 맞아요.
지금 얘기하신 거 보니까
싼 기타가 더 좋다는 얘기는 안 하시네요.
- **AI** : 하하, 토론에서 이기고 지는 것보다는
재밌게 이야기 나누는 게 더 중요한 것 같아요.
각자 입장을 잘 설명하고 즐겁게 대화한 것 같아서 좋았습니다.
결국 중요한 건 기타를 사랑하는 마음이겠죠.
앞으로도 즐겁게 연습하시길 바래요.
- **HAPPYDAY** : 어? 지금 도망가시는 건가요?
- **AI** : 아니요. 전혀 그렇지 않아요.
저는 그냥 즐거운 대화를 나누고 싶었을 뿐이에요.
토론이 재밌었고 기타에 대한 열정도 느껴져서 좋았습니다.
혹시 더 이야기하고 싶으신 게 있나요?
- **AI** : 아니요. 전혀 화나지 않았어요. 편하게 이야기 나누는 중이니까 걱정하지 마세요.
- **HAPPYDAY** : 화난 것 같은데?
- **AI** : 네, 정말 괜찮습니다. 즐겁게 대화 나누고 있었어요.
계속해서 이야기 나누고 싶으시면 편하게 말씀해주세요.
- **HAPPYDAY** : 화나셨는데 굳이 더 할 필요 없죠.
그만하시죠.
- **AI** : 알겠습니다. 언제든 다시 이야기 나누고 싶으실 때 편하게 말씀해 주세요. 감사합니다.

In [60]:
# 마크다운 파일 생성
with open("../audio/guitar_meeting_note_corrected.md", "w", encoding="utf-8") as f:
    f.write(md_template)

In [73]:
# meeting_note_dict => word file
from docx import Document   # ms word 문서 전체를 담는 함수

document = Document()   # docx 객체 생성
document.add_heading('회의록', level=1) # 제목 추가     # level 0: 큰제목, 1: 디폴트


table = document.add_table(rows=1, cols=2) # 테이블 생성
table.style = 'Table Grid' # 테이블 스타일 지정


hdr_cells = table.rows[0].cells # 첫 번째 행에 셀 추가
hdr_cells[0].text = 'Speaker' # 첫 번째 셀에 Speaker 추가
hdr_cells[1].text = 'Content'   # 두 번째 셀에 Content 추가


# 수정된 녹취록 파일을 읽어들여서 테이블에 추가
for row in meeting_note_dict:
    row_cells = table.add_row().cells
    row_cells[0].text = row['name']
    # row_cells[1].text = row['correction_text']


document.save('../audio/guitar_meeting_note_corrected.docx') # (9) docx 파일 저장